import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
const load=async name=>import(`data:text/javascript;base64,${Buffer.from(stripTypeScriptTypes(readFileSync(new URL(`../src/lib/${name}.ts`,import.meta.url),'utf8'))).toString('base64')}`);
const {coalesceRefresh}=await load('refreshQueue');
let release, inFlight=0, peak=0; const calls=[];
const queue=coalesceRefresh(async(quiet,full)=>{
  inFlight++; peak=Math.max(peak,inFlight); calls.push([quiet,full]);
  if(calls.length===1) await new Promise(resolve=>release=resolve);
  inFlight--;
});
const first=queue(true,false);await Promise.resolve();
const rest=Array.from({length:20},()=>queue(true,false));
rest.push(queue(false,true));release();await Promise.all([first,...rest]);
assert.equal(peak,1);assert.deepEqual(calls,[[true,false],[false,true]]);
await queue(true,false);assert.equal(calls.length,3,'a later refresh must still run');
let fails=true;
const retry=coalesceRefresh(async()=>{if(fails)throw new Error('test failure');});
await assert.rejects(retry(),/test failure/);fails=false;await retry();
const {businessExport}=await load('businessExport');
const doc=businessExport({workOrders:[{id:'one'}],expenses:[]},'org','owner','2026-10-09T00:00:00Z');
assert.equal(doc.completeDatabaseBackup,false);assert.equal(doc.counts.workOrders,1);
assert.ok(doc.excluded.some(item=>item.includes('Storage')));
assert.ok(doc.excluded.some(item=>item.includes('权限')));
assert.equal(doc.organizationId,'org');assert.equal(doc.data.workOrders[0].id,'one');
const main=readFileSync(new URL('../src/main.tsx',import.meta.url),'utf8');
const exportFunction=main.slice(main.indexOf('const downloadBackup ='),main.indexOf('function PrintMenu'));
assert.ok(exportFunction.includes('await cloud.loadStore(undefined, true)'));
assert.ok(!main.includes('下载全部资料备份'));
console.log('PASS: 21 refresh events coalesce to one follow-up, serialized reads, forced refresh retained, error recovery, fresh scoped export and honest backup manifest');
