import { useState } from 'react';
import './publicWebsite.css';
import { OilChangeRewardsPage } from './OilChangeRewardsPage';

const business = {
  name: 'Z&G Auto Body And Repair',
  address: '319 Agostino Rd, San Gabriel, CA 91776',
  phone: '626-508-0888',
  email: 'zgauto319@gmail.com',
  hours: 'Monday–Saturday, 9:00 AM–6:00 PM',
};
const publicUrl = (path: string) => window.location.pathname.startsWith('/website') ? `/website${path === '/' ? '' : path}` : path;

function Header() {
  return <header className="public-header"><a className="public-brand" href={publicUrl('/')}><span>Z&amp;G</span><b>AUTO BODY AND REPAIR</b></a><nav><a href={`${publicUrl('/')}#services`}>Services</a><a href={publicUrl('/oil-change-rewards')}>Oil Rewards / 机油活动</a><a href={`${publicUrl('/')}#contact`}>Contact</a><a href={publicUrl('/privacy')}>Privacy</a><a href={publicUrl('/terms')}>SMS Terms</a></nav><a className="public-call" href="tel:+16265080888">Call {business.phone}</a></header>;
}

function Footer() {
  return <footer className="public-footer"><div><b>{business.name}</b><span>{business.address}</span><span>{business.phone} · {business.email}</span></div><div><a href={publicUrl('/privacy')}>Privacy Policy</a><a href={publicUrl('/terms')}>Terms &amp; SMS Policy</a><a href="https://app.zgautorepair.com">Employee Login</a></div><small>© 2026 {business.name}. All rights reserved.</small></footer>;
}

function Home() {
  const [form, setForm] = useState({ name: '', phone: '', vehicle: '', message: '', consent: false });
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    const subject = encodeURIComponent(`Service request from ${form.name}`);
    const body = encodeURIComponent(`Name: ${form.name}\nPhone: ${form.phone}\nVehicle: ${form.vehicle}\nRequest: ${form.message}\n\nSMS consent: Yes — customer requested transactional repair updates and accepted the displayed SMS terms.`);
    window.location.href = `mailto:${business.email}?subject=${subject}&body=${body}`;
  };
  return <><Header /><main className="public-site"><section className="public-hero"><div><p className="public-kicker">SAN GABRIEL, CALIFORNIA</p><h1>Professional auto repair.<br /><em>Clear communication.</em></h1><p>Maintenance, diagnostics, mechanical repair and auto body service for individual drivers and commercial fleets.</p><div className="public-hero-actions"><a className="public-primary" href="tel:+16265080888">Call for service</a><a href="#contact">Request an appointment</a></div><div className="public-trust"><span>Mon–Sat 9 AM–6 PM</span><span>English · 中文</span><span>Repair updates by email or SMS</span></div></div><div className="public-hero-card"><span>Z&amp;G</span><h2>Auto Body<br />And Repair</h2><p>319 Agostino Rd<br />San Gabriel, CA 91776</p><a href="https://maps.google.com/?q=319+Agostino+Rd+San+Gabriel+CA+91776">Get directions →</a></div></section>
  <section id="services" className="public-section"><p className="public-kicker">OUR SERVICES</p><h2>Complete care for your vehicle</h2><div className="public-services"><article><b>01</b><h3>Maintenance</h3><p>Oil service, fluids, filters, batteries and preventive inspections.</p></article><article><b>02</b><h3>Diagnostics &amp; Repair</h3><p>Check-engine diagnosis, brakes, cooling, electrical and mechanical repairs.</p></article><article><b>03</b><h3>Auto Body</h3><p>Collision assessment, body repair coordination and vehicle condition documentation.</p></article><article><b>04</b><h3>Fleet Service</h3><p>Work orders, driver contacts, repair approvals and monthly account support.</p></article></div></section>
  <section className="public-process"><div><p className="public-kicker">HOW IT WORKS</p><h2>Know what is happening at every step.</h2></div><ol><li><b>Inspect</b><span>We document the vehicle and your concerns.</span></li><li><b>Approve</b><span>You review the estimate before authorized work begins.</span></li><li><b>Repair</b><span>Receive transactional progress and completion updates.</span></li></ol></section>
  <section id="contact" className="public-contact"><div><p className="public-kicker">CONTACT US</p><h2>Request service</h2><p><b>{business.name}</b><br />{business.address}<br />{business.hours}</p><p><a href="tel:+16265080888">{business.phone}</a><br /><a href={`mailto:${business.email}`}>{business.email}</a></p></div><form onSubmit={submit}><label>Name<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})} /></label><label>Mobile number<input required type="tel" value={form.phone} onChange={e => setForm({...form,phone:e.target.value})} /></label><label>Vehicle<input required value={form.vehicle} onChange={e => setForm({...form,vehicle:e.target.value})} placeholder="Year, make and model" /></label><label>Service requested<textarea required value={form.message} onChange={e => setForm({...form,message:e.target.value})} /></label><label className="public-consent"><input required type="checkbox" checked={form.consent} onChange={e => setForm({...form,consent:e.target.checked})} /><span>I agree to receive transactional SMS messages from {business.name} about this service request, estimates, repair authorization, progress, invoices and pickup. Message frequency varies, generally up to 10 messages per repair order. Message and data rates may apply. Reply STOP to opt out or HELP for help. Consent is not a condition of purchase. See our <a href={publicUrl('/terms')}>SMS Terms</a> and <a href={publicUrl('/privacy')}>Privacy Policy</a>.</span></label><button className="public-primary">Prepare service request</button></form></section></main><Footer /></>;
}

function Privacy() {
  return <><Header /><main className="public-legal"><p className="public-kicker">LAST UPDATED JULY 17, 2026</p><h1>Privacy Policy</h1><p>{business.name} respects the privacy of customers and website visitors. This policy explains how we collect and use information in connection with estimates, repairs, invoices and customer communications.</p><h2>Information we collect</h2><p>We may collect your name, address, email address, telephone number, vehicle and VIN information, repair history, photographs, signatures, estimates, invoices and payment records. We also receive information that you voluntarily submit through our website, by telephone, in person or through a repair order.</p><h2>How we use information</h2><p>We use this information to schedule and perform automotive services, prepare estimates and invoices, obtain repair authorization, provide repair-status and pickup notifications, maintain service records, process payments, prevent fraud and comply with legal obligations.</p><h2>Mobile information and SMS</h2><p><strong>We do not sell, rent, or share mobile phone numbers or SMS consent information with third parties or affiliates for marketing or promotional purposes.</strong> We may disclose information to service providers only as necessary to operate our communications and business services, or when required by law. SMS message frequency varies, generally up to 10 messages per repair order. Message and data rates may apply. Reply STOP to opt out or HELP for help.</p><h2>Data protection and retention</h2><p>We use reasonable administrative and technical safeguards. Records are retained as reasonably necessary for business, warranty, accounting and legal purposes. No internet or storage system can be guaranteed completely secure.</p><h2>Your choices</h2><p>You may request access, correction or deletion of eligible personal information by contacting us. You may opt out of SMS messages at any time by replying STOP.</p><h2>Contact</h2><p>{business.name}<br />{business.address}<br /><a href={`mailto:${business.email}`}>{business.email}</a> · <a href="tel:+16265080888">{business.phone}</a></p></main><Footer /></>;
}

function Terms() {
  return <><Header /><main className="public-legal"><p className="public-kicker">LAST UPDATED JULY 17, 2026</p><h1>Terms of Service &amp; SMS Terms</h1><h2>Automotive services</h2><p>Estimates are based on the information available at inspection and may change if additional issues are discovered. Work begins only after authorization. Final pricing, warranty coverage and payment terms are stated on the applicable repair order or invoice.</p><h2>Z&amp;G transactional SMS program</h2><p>Customers may expressly opt in through our service-request form, repair intake process, written repair order or another documented consent method. Messages may include appointment information, estimates, authorization links, repair progress, invoices, payment reminders and pickup notifications. We do not send unrelated third-party marketing messages.</p><ul><li><b>Brand:</b> {business.name}</li><li><b>Frequency:</b> Varies by service activity, generally up to 10 messages per repair order.</li><li><b>Charges:</b> Message and data rates may apply.</li><li><b>Opt out:</b> Reply STOP to unsubscribe. We may send one final confirmation message.</li><li><b>Help:</b> Reply HELP, call {business.phone}, or email {business.email}.</li><li><b>Consent:</b> Consent to SMS is not a condition of purchasing goods or services.</li></ul><p>Wireless carriers are not liable for delayed or undelivered messages. You are responsible for providing a mobile number you control and notifying us if it changes. We may modify or discontinue the messaging program when permitted by law.</p><h2>Privacy</h2><p>Mobile information and SMS consent are handled as described in our <a href={publicUrl('/privacy')}>Privacy Policy</a> and are not shared with third parties or affiliates for their marketing or promotional purposes.</p><h2>Contact</h2><p>{business.name}<br />{business.address}<br /><a href={`mailto:${business.email}`}>{business.email}</a> · <a href="tel:+16265080888">{business.phone}</a></p></main><Footer /></>;
}

export function PublicWebsite({ path }: { path: string }) {
  if (path.startsWith('/oil-change-rewards')) return <OilChangeRewardsPage Header={Header} Footer={Footer} />;
  if (path.startsWith('/privacy')) return <Privacy />;
  if (path.startsWith('/terms')) return <Terms />;
  return <Home />;
}
